name: Build GKI & Generic 32 Images

on:
  workflow_dispatch:
 
    inputs:
      build_target:
        description: 'Build target: gki-5.10 or generic-32'
        required: true
        default: 'gki-5.10'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

         - name: Set up Docker
        run: |
          sudo apt-get update
          # Remove potential conflicting package before installing docker.io
          sudo apt-get remove -y containerd || true
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo usermod -aG docker $USER

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git make curl wget gdisk parted \
            adb fastboot android-sdk-libsparse-utils \
            python3 python3-pip \
            qemu-user-static debootstrap schroot lxc lxd \
            build-essential devscripts crossbuild-essential-arm64 \
            android-sdk-platform-tools-common repo python3-pycryptodome gzip lz4 locales

      - name: Set up locales
        run: |
          sudo locale-gen en_US.UTF-8
          export LANG=en_US.UTF-8

      - name: Run setup.sh
        run: |
          chmod +x setup.sh
          ./setup.sh

      - name: Build Nethunter-Halium Image
        run: |
          chmod +x build.sh
          ./build.sh ${{ github.event.inputs.build_target }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nethunter-halium-${{ github.event.inputs.build_target }}
          path: build/out/nethunter-halium-*.img
